language: scala

scala:
- 2.10.3

notifications:
  email:
  - viktor@farcic.com

before_install:
  - npm install -g grunt-cli
  - npm install -g gulp
  - npm install
  - bower install

script:
  - sbt ++2.10.3 test
  - gulp test
